# NginX Local
#

version: '3.7'

services:

  # NginX 
  web:
    image: nginx:1.18.0-alpine
    ports:
      - "9001:5080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web_html:/etc/nginx/html
    networks:
      - front

networks:
  front:
    driver: bridge
